onless/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render

from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
from django.views.static import serve

from onless.api import sms_api_result


def trigger_error(request):
    division_by_zero = 1 / 0



urlpatterns = [
                  path('yoz/', admin.site.urls),
                  path('', include('landing.urls')),
                  path('video/', include('video.urls')),

                  path('sms-api-result/', sms_api_result),

                  path('sign/', include('sign.urls')),
                  path('user/', include('user.urls')),
                  path('quiz/', include('quiz.urls')),
                  path('practical/', include('practical.urls')),
                  path('accounts/', include('allauth.urls')),
                  # path('payments/', include('payments.urls')),
                  # path('payments/', include('click.urls')),
                  # path('paycom/', TestView.as_view()),

                  path('click/', include('click.urls')),
                  # path('summernote/', include('django_summernote.urls')),
                  path('sentry-debug/', trigger_error),

                  path('error-403/', TemplateView.as_view(template_name='inc/403.html', ),
                       name='error_403'),
                  path('error-404/', TemplateView.as_view(template_name='inc/404.html', ),
                       name='error_404'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "user.views.handler404"

quiz/urls.py
from django.urls import path, include
from .views import *

app_name = 'quiz'

urlpatterns = [
    path('add_result/', add_result, name='add_result'),
    path('get-true-answer/', get_true_answer, name='get_true_answer'),
    path('select-lang/', select_lang, name='select_lang'),
    path('select-type/', select_type, name='select_type'),
    path('select-bilet/', select_bilet, name='select_bilet'),
    path('get_bilet_color/', get_bilet_color, name='get_bilet_color'),
    path('reset-answers/', reset_answers, name='reset_answers'),

]

user/urls.py
from django.urls import path, include
from .views import *

app_name = 'user'

urlpatterns = [
    path('', user_login, name='login'),
    path('add/', add_list, name='add_list'),
    path('settings/', settings_list, name='settings_list'),
    path('worker-add/', worker_add, name='worker_add'),
    path('group/<int:id>/add-pupil/', AddPupil.as_view(), name='add_pupil'),
    path('add-group/', add_group, name='add_group'),
    path('groups/', groups_list, name='groups_list'),
    path('group/<int:id>/', group_detail, name='group_detail'),
    path('group-delete/<int:id>/', group_delete, name='group_delete'),
    path('group-update/<int:id>/', group_update, name='group_update'),
    path('profil-edit/', profil_edit, name='edit_profil'),
    path('school-edit/', school_edit, name='edit_school'),
    path('pupil-edit/<int:id>/', pupil_edit, name='edit_pupil'),
    path('contact/', contact, name='contact'),
    path('search/', search, name='search'),
    path('pupil-delete/<int:id>/', pupil_delete, name='pupil_delete'),
    path('workers/', workers_list, name='workers_list'),
    path('worker-edit/<int:id>/', worker_edit, name='worker_edit'),
    path('worker-delete/<int:id>/', worker_delete, name='worker_delete'),
    path('upload-file/', upload_file, name='upload_file'),
    path('group/<int:id>/create-pupil-with-excel/', CreatePupilWithExcel.as_view(), name='create_pupil_with_excel'),
    path('bugalter/groups/', bugalter_groups_list, name='bugalter_groups_list'),
    path('bugalter/group/<int:id>/', bugalter_group_detail, name='bugalter_group_detail'),
    path('set-pay/', set_pay, name='set_pay'),
    path('remove-pay/<int:id>/', remove_pay, name='remove_pay'),
    path('pay-history/<int:user_id>/<int:group_id>/', pay_history, name='pay_history'),
    path('history/view-video/all/', history_view_video_all, name='history_view_video_all'),
    path('history-view-video-all/', HistoryViewVideoAll.as_view(), name='HistoryViewVideoAll'),

    path('history/pupil-view-video/<int:id>/', history_pupil_view_video, name='history_pupil_view_video'),
    path('history-pupil-view-video/<int:id>/', HistoryPupilViewVideo.as_view(), name='HistoryPupilViewVideo'),
    path('get-district/', get_district, name='get_district'),
    path('getDistrict/', getDistrict, name='getDistrict'),

    path('school-groups/<int:id>/', school_groups, name='school_groups'),
    path('school-group/<int:id>/', school_group_detail, name='school_group_detail'),
    path('support/', support, name='support'),
    path('result/<int:id>/', result, name='result'),
    path('news-messages/', news_messages, name='news_messages'),
    path('get-learning-type/', get_learning_type, name='get_learning_type'),

    path('attendance-groups-list/', attendance_groups_list, name='attendance_groups_list'),

    path('attendance-set-by-group/<int:id>/', attendance_set_by_group, name='attendance_set_by_group'),
    path('attendance-set-by-subject/<int:group_id>/<int:subject_id>/', attendance_set_by_subject,
         name='attendance_set_by_subject'),
    path('attendance-set-visited/', attendance_set_visited, name='attendance_set_visited'),
    path('send-sms/', send_sms, name='send_sms'),
    path('send-sms/list/', SendSmsList, name='send_sms_list'),

    path('referral-list/<int:id>/', referral_list, name='referral_list'),

    path('rating-groups-list/', rating_groups_list, name='rating_groups_list'),
    path('rating-set-by-group/<int:id>/', rating_set_by_group, name='rating_set_by_group'),
    path('rating-set-by-subject/<int:group_id>/<int:subject_id>/', rating_set_by_subject, name='rating_set_by_subject'),
    path('electronical-journal/', electronical_journal, name='electronical_journal'),
    path('rating-create/', rating_create, name='rating_create'),
    path('get-group-pupils-count/', get_group_pupils_count, name='get_group_pupils_count'),
    path('get-workers-count/', get_workers_count, name='get_workers_count'),
    # path('get-attendance-time/', get_attendance_time, name='get_attendance_time'),
    path('get-group-months/', get_group_months, name='get_group_months'),
    path('sms-settings/', SmsSettings.as_view(), name='sms_settings'),
    path('buy-simple-sms/', BuySimpleSms.as_view(), name='buy_simple_sms'),
    path('buy-add-pupil-sms/', BuyAddPupilSms.as_view(), name='buy_add_pupil_sms'),

    path('modify-checkbox-send-sms/', modify_checkbox_send_sms, name='modify_checkbox_send_sms'),
    path('payment-payme/', payment_payme, name='payment_payme'),
    path('personal-exam-doc-generate/<int:id>/', personal_exam_doc_generate, name='personal_exam_doc_generate'),

    path('again-send-sms/<int:pupil_id>/', again_send_sms, name='again_send_sms'),

    path('error/403/', error_403, name='error_403'),
    path('handler404/', handler404, name='handler404'),
]

user/views.py
import json
import random
import re
import shutil
from random import randrange
from datetime import datetime as dt
import datetime

import pytz
import requests
import xlrd
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.humanize.templatetags.humanize import intcomma
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import ProtectedError, Q
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic import *
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment
from openpyxl.utils import get_column_letter

from onless import settings
from onless.api import SUCCESS, FAILED, INVALID_NUMBER, MESSAGE_IS_EMPTY, SMS_NOT_FOUND, SMS_SERVICE_NOT_TURNED, \
    GetStatusSms, SendSmsWithPlayMobile
from onless.settings import *
from quiz.models import *
from sign.models import Material
from user.decorators import *

from .decorators import *
from .forms import *
from user.models import *
from video.views import *
from video.models import *
from sign.models import *
from .mixins import AllowedRolesMixin
from .models import *
from django.db import IntegrityError, transaction
import pandas as pd
import calendar
from calendar import month_name

#
from .serializers import CreatePupilSerializer
from .utilities import parse_excel_pupil
from .utils import render_to_pdf
from docxtpl import DocxTemplate
from rest_framework import generics


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        username = get_pasport(username)
        password = request.POST['password'].replace(' ', '')
        user = authenticate(username=username, password=password)
        if user is not None:
            # if user.is_active and user.school.is_block == False:
            if user.is_active:
                login(request, user)
                return redirect(reverse_lazy('landing:home'))
            else:
                messages.error(request, 'Siz bloklangansiz !')
                return HttpResponseRedirect('/accounts/login/')
        else:
            messages.error(request, "Login yoki parol noto'g'ri!")
            return HttpResponseRedirect('/accounts/login/')


@login_required
def add_list(request):
    if request.user.role == '2' or request.user.role == '3':
        return render(request, 'inc/add_list.html')
    else:
        return render(request, 'inc/404.html')


@login_required
def settings_list(request):
    return render(request, 'user/settings_list.html')


@login_required
def worker_add(request):
    if request.user.role == '2':
        if request.method == 'POST':
            form = AddUserForm(data=request.POST)
            password = random.randint(1000000, 9999999)
            school = get_object_or_404(School, id=request.user.school.id)
            if form.is_valid():
                name = form.cleaned_data['name']
                name = get_name(name)
                username = get_pasport(request.POST['pasport'])
                worker = request.POST.get('worker')
                if worker == 'instructor':
                    role = 6
                elif worker == 'accountant':
                    role = 5
                else:
                    role = 3

                try:
                    user = User.objects.create_user(
                        username=username,
                        pasport=username,
                        school=school,
                        turbo=password,
                        password=password,
                        name=name,
                        phone=form.cleaned_data['phone'],
                        role=str(role),
                        is_superuser=False,
                    )
                    user.set_password(password)
                    user.username = username
                    user.email = ''
                    user.save()

                    if school.send_sms_add_worker:
                        r = SendSmsWithApi(user=user, is_add_worker=True).get()
                        print(f"response: {r}")
                        if r == SUCCESS:
                            messages.success(request,
                                             f"{user.name} muvaffaqiyatli qo'shildi! Sms muvaffaqiyatli jo'natildi!")
                        elif r == INVALID_NUMBER:
                            user.delete()
                            messages.error(request, f"{user.phone} raqam noto'g'ri kiritilgan!")
                        elif r == MESSAGE_IS_EMPTY:
                            user.delete()
                            messages.error(request, "Xabar matni kiritilmagan!")
                        elif r == SMS_NOT_FOUND:
                            user.delete()
                            messages.error(request, "Sizda sms to'plami mavjud emas!")
                        elif r == SMS_SERVICE_NOT_TURNED:
                            user.delete()
                            messages.error(request, "Sms xizmati faollashtirilmagan!")
                        else:
                            user.delete()
                            messages.error(request, "Xatolik yuz berdi!")
                    else:
                        messages.success(request,
                                         f"{user.name} muvaffaqiyatli qo'shildi! Sms xizmati o'chirilganligi sababli sms yuborilmadi")
                except IntegrityError:
                    messages.error(request, "Bu pasport oldin ro'yhatdan o'tkazilgan !")
            else:
                messages.error(request, "Forma to'liq yoki to'g'ri to'ldirilmagan !")
        else:
            form = AddUserForm(request)
        return render(request, 'user/worker_add.html', )
    else:
        return render(request, 'inc/404.html')


class AddPupil(AllowedRolesMixin, View):
    allowed_roles = [DIRECTOR, TEACHER]

    def dispatch(self, *args, **kwargs):
        try:
            group = Group.objects.filter(id=kwargs.get('id')).last()
            if self.request.user.school == group.school:
                return super(AllowedRolesMixin, self).dispatch(*args, **kwargs)
            return redirect(reverse_lazy('error_403'))
        except Exception as e:
            print(e)
            return redirect(reverse_lazy('error_403'))

    def get(self, request, *args, **kwargs):
        context = {
            'group_id': self.kwargs.get('id')
        }
        return render(request, 'user/pupil/add_pupil.html', context)

    def post(self, request, *args, **kwargs):
        school = get_object_or_404(School, id=request.user.school.id)
        if school.add_pupil_sms_count <= 0:
            messages.error(request,
                           "Sizda smslar mavjud emas! O'quvchi qo'shish uchun kiritish sms xarid qiling! <a href='{0}'>Sms xarid qilish uchun ushbu havolaga bosing</a>".format(
                               reverse('user:sms_settings')))
            return redirect(reverse_lazy('user:add_pupil', kwargs={'id': self.kwargs.get('id')}))
        serializer = CreatePupilSerializer(data=request.POST,
                                           context={'request': request, 'group_id': kwargs.get('id')})
        if serializer.is_valid():
            serializer.save()
            r = SendSmsWithPlayMobile(user=serializer.instance, is_add_pupil=True).get()
            # r = {'status': SUCCESS, 'result': "Test"}
            if r['status'] == SUCCESS:
                messages.success(request, "O'quvchi muvaffaqiyatli qo'shildi! " + r['result'])
            else:
                messages.warning(request, "O'quvchi muvaffaqiyatli qo'shildi! " + r['result'])
        else:
            try:
                message = next(iter(dict(serializer.errors).values()))[0]
                messages.error(request, message)
            except:
                messages.error(request, serializer.errors)
        return self.get(request, *args, **kwargs)


@login_required
def add_group(request):
    if request.user.role == '2':
        teachers = User.objects.filter(
            Q(role=3, school=request.user.school) | Q(role=2, school=request.user.school)).order_by('name')
        context = {
            'teachers': teachers,
        }
        if request.POST:
            form = AddGroupForm(request.POST)
            if form.is_valid():
                number = form.cleaned_data['number']
                category = request.POST['category']
                teacher = form.cleaned_data['teacher']
                form = form.save(commit=False)
                form.number = number
                if request.POST['price']:
                    price = request.POST['price']
                    form.price = price
                form.category = category
                form.teacher = teacher
                form.school = request.user.school
                form.start = request.POST['start']
                form.stop = request.POST['stop']
                form.save()
                messages.success(request, f"{form.category}-{form.number}-{form.year} guruh qo'shildi")
        else:
            form = AddGroupForm()
        return render(request, 'user/group/add_group.html', context)
    elif request.user.role == '3':
        if request.POST:
            form = AddTeacherGroupForm(request.POST)
            if form.is_valid():
                number = form.cleaned_data['number']
                category = request.POST['category']
                teacher = get_object_or_404(User, id=request.user.id)
                price = form.cleaned_data['price']
                form = form.save(commit=False)
                form.number = number

templates/user/attendance/attendance_groups_list.html
{% extends 'base.html' %}
{% load user_tags %}

{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Davomat" "user:attendance_groups_list" %}
{% endblock %}

{% block content %}
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Guruhlar ro'yhati</h3>
                </div>
                {% include 'inc/messages_part.html' %}

                <div class="card-body">
                    <div class="table-responsive">
                        <table id="example1" style="font-size: 0.9rem"
                               class="table table-bordered table-hover table-responsive">
                            <thead>
                            <tr style="background-color: #ecebeb">
                                <th style="width: 3%">№</th>
                                <th>Guruh nomi</th>
                                <th>An'anaviy ta'lim oluvchilar</th>

                                <th>Davomatni belgilash</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for group in groups %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    {% get_fullname_group group.id as group_name %}
                                    <td>
                                        {% if request.user.role == '2' or request.user.role == '3' %}
                                            <a href="{% url 'user:attendance_set_by_group' group.id %}">
                                                <b id="group_name">{{ group_name }}</b>
                                            </a>
                                        {% else %}
                                            <b id="group_name">{{ group_name }}</b>
                                        {% endif %}
                                    </td>

                                    <td>{% for pupil_count in group.group_user.all|get_offline_pupils %}
                                        {{ pupil_count }}
                                    {% endfor %}
                                    </td>

                                    <td><a class="btn btn-info"
                                           href="{% url 'user:attendance_set_by_group' group.id %}">Davomatni
                                        belgilash</a></td>
                                </tr>

                            {% endfor %}
                            </tbody>
                            <tfoot>

                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block bottom %}

    <link data-require="sweet-alert@*" data-semver="0.4.2" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css"/>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>

        function delete_group(group_id, group_name) {
            var groupId = group_id;
            var groupName = group_name;

            swal({
                title: "Guruhni o'chirmoqchimisiz ?",
                text: "Siz haqiqatdan ham " + groupName + " guruhini o'chirmoqchimisiz ?",
                icon: "warning",
                closeOnClickOutside: false,
                buttons: [
                    'Yoq, Bekor qilish!',
                    'Ha, Roziman!'
                ],
                dangerMode: true,
            }).then(function (isConfirm) {
                if (isConfirm) {
                    swal({
                        title: "Muvaffaqiyatli o'chirildi !",
                        text: groupName + " guruhi muvaffaqiyatli o'chirildi !",
                        icon: 'success'
                    }).then(function () {
                        $.ajax({
                            type: 'GET',
                            url: '/user/group-delete/' + groupId,
                        });
                        window.location.href = '{% url "user:groups_list" %}';
                    });
                } else {
                    swal("Bekor qilindi", groupName + " guruhingiz ro'yhatda turibti !", "error");
                }
            });
        }

    </script>

{% endblock bottom %}

templates/user/attendance/attendance_set_by_group.html
{% extends 'base.html' %}
{% load quiz_tags %}
{% load user_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Davomat" "user:attendance_groups_list" %}
    {% get_fullname_group group.id as get_group %}
    {% breadcrumb get_group "user:attendance_set_by_group" group.id %}

{% endblock %}

{% block content %}
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">{{ group.category }}-{{ group.number }} {{ group.year }} guruhi jadval bo'yicha fanlar ro'yhati</h3>
                </div>

                {% include 'inc/messages_part.html' %}

                <!-- /.card-header -->
                <!-- form start -->
                <div class="card-body">
                    <div class="table-responsive">
                        <table style="font-size: 0.9rem" id="example1"
                               class="table table-bordered table-hovered table-hover">
                            <thead>
                            <tr style="background-color: #ecebeb">
                                <th style="width: 2%">№</th>
                                <th>Fan nomi</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for subject in subjects %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><b><a href="{% url 'user:attendance_set_by_subject' group.id subject.id %}">{{ subject.short_title }} &nbsp; - &nbsp; {{ subject.long_title }}</a></b>
                                    </td>

                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>

                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/user/attendance/attendance_set_by_subject.html
{% extends 'base.html' %}
{% load quiz_tags %}
{% load user_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Davomat" "user:attendance_groups_list" %}
    {% get_fullname_group group.id as get_group %}
    {% breadcrumb get_group "user:attendance_set_by_group" group.id %}
    {% breadcrumb subject.long_title "user:attendance_set_by_subject" group.id subject.id %}

{% endblock %}


{% block content %}
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Guruh: &nbsp<b>{{ group.category }}-{{ group.number }} {{ group.year }}</b>
                        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Fan: <b>{{ subject.short_title }}</b>
                        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                        Sana: <b>{% now "SHORT_DATE_FORMAT" %}</b></h3>
                </div>

                {% include 'inc/messages_part.html' %}

                <!-- /.card-header -->
                <!-- form start -->
                <div class="card-body">
                    <div class="table-responsive">
                        <table style="font-size: 0.9rem" id="example1"
                               class="table table-bordered table-hovered table-hover">
                            <thead>
                            <tr style="background-color: #ecebeb">
                                <th style="width: 2%">№</th>
                                <th>O'quvchining ism familiyasi</th>
                                <th>Davomatni belgilash</th>
                                <th>Belgilangan vaqt</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for pupil in pupils %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><b>{{ pupil.name }}</b>
                                    </td>
                                    <td class="parentBtn">
                                        {% get_pupil_attendance pupil.id subject.id request.user.id as visited %}
                                        <button {% if visited == True %} disabled{% endif %} data-id="{{ pupil.id }}"
                                                                         class="btn btn-success visited">Kelgan
                                        </button>
                                        <button {% if visited == False %} disabled {% endif %}
                                                                                             data-id="{{ pupil.id }}"
                                                                                             class="btn btn-danger not_visited">
                                            Kelmagan
                                        </button>


                                    </td>
                                    {% get_pupil_attendance_time pupil.id subject.id as time %}
                                    <td data-id="{{ pupil.id }}"
                                        class="attendance_time">{% if time %}{{ time|date:'SHORT_DATETIME_FORMAT' }}{% else %}<span style="color: red">davomat belgilanmagan</span>{% endif %}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                            <tfoot>

                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block bottom %}

    <link data-require="sweet-alert@*" data-semver="0.4.2" rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css"/>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        $(document).ready(function () {
            var subjectId = '{{ subject.id }}'

            $('.visited').on('click', function () {
                var pupilId = $(this).data('id'),
                    visited = true

                clickBtnSetAttendance(pupilId, visited, subjectId)

            })

            $('.not_visited').on('click', function () {
                var pupilId = $(this).data('id'),
                    visited = false

                clickBtnSetAttendance(pupilId, visited, subjectId)

            })

            var csrftoken = getCookie('csrftoken');

            $.ajaxSetup({
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('X-CSRFToken', csrftoken)
                }
            })


            function clickBtnSetAttendance(pupilId, visited, subjectId) {

                $.ajax({
                    type: 'GET',
                    url: '{% url "user:attendance_set_visited" %}',
                    data: {
                        'pupil': pupilId,
                        'subject': subjectId,
                        'visited': visited
                    },
                    success: function (response) {
                        if (response !== 'False') {

                            $(".attendance_time").each(function () {

                                if ($(this).data('id') === pupilId) {
                                    $(this).data('id', pupilId).text(response)
                                }
                            });

                            if (visited === true) {

                                $('.visited').each(function () {

                                    if ($(this).data('id') === pupilId) {
                                        $(this).attr('disabled', true)
                                    }
                                })

                                $('.not_visited').each(function () {

                                    if ($(this).data('id') === pupilId) {
                                        $(this).attr('disabled', false)
                                    }
                                })

                            } else {
                                $('.visited').each(function () {

                                    if ($(this).data('id') === pupilId) {
                                        $(this).attr('disabled', false)
                                    }
                                })

                                $('.not_visited').each(function () {

                                    if ($(this).data('id') === pupilId) {
                                        $(this).attr('disabled', true)
                                    }
                                })
                            }

                        } else {
                            errorFunction()
                            console.log(response)
                        }
                    },
                    error: function (response) {
                        errorFunction()
                        console.log(response)
                    }
                })
            }

        });


    </script>


{% endblock bottom %}