onless/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render

from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
from django.views.static import serve

from onless.api import sms_api_result


def trigger_error(request):
    division_by_zero = 1 / 0



urlpatterns = [
                  path('yoz/', admin.site.urls),
                  path('', include('landing.urls')),
                  path('video/', include('video.urls')),

                  path('sms-api-result/', sms_api_result),

                  path('sign/', include('sign.urls')),
                  path('user/', include('user.urls')),
                  path('quiz/', include('quiz.urls')),
                  path('practical/', include('practical.urls')),
                  path('accounts/', include('allauth.urls')),
                  # path('payments/', include('payments.urls')),
                  # path('payments/', include('click.urls')),
                  # path('paycom/', TestView.as_view()),

                  path('click/', include('click.urls')),
                  # path('summernote/', include('django_summernote.urls')),
                  path('sentry-debug/', trigger_error),

                  path('error-403/', TemplateView.as_view(template_name='inc/403.html', ),
                       name='error_403'),
                  path('error-404/', TemplateView.as_view(template_name='inc/404.html', ),
                       name='error_404'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "user.views.handler404"

quiz/urls.py
from django.urls import path, include
from .views import *

app_name = 'quiz'

urlpatterns = [
    path('add_result/', add_result, name='add_result'),
    path('get-true-answer/', get_true_answer, name='get_true_answer'),
    path('select-lang/', select_lang, name='select_lang'),
    path('select-type/', select_type, name='select_type'),
    path('select-bilet/', select_bilet, name='select_bilet'),
    path('get_bilet_color/', get_bilet_color, name='get_bilet_color'),
    path('reset-answers/', reset_answers, name='reset_answers'),

]

quiz/models.py
from django.db import models
from django.utils import timezone

from user.models import User
from video.models import Video
from . import fields

class Answer(models.Model):
    text = models.CharField(max_length=600)
    questions = models.ForeignKey('Question', on_delete=models.SET_NULL, related_name='answers', null=True)
    is_true = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Question(models.Model):
    title = models.CharField(max_length=600)
    video = models.ForeignKey(Video, on_delete=models.SET_NULL, null=True)
    img = models.ImageField(upload_to='quiz/img/%Y-%m-%d/', blank=True, default='')
    is_active = models.BooleanField(default=True)
    is_test = models.BooleanField(default=False)
    pub_date = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.title

class Bilet(models.Model):
    number = models.IntegerField(blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.number}"

BILET_SAVOL = (
    ('1','1'),
    ('2','2'),
    ('3','3'),
    ('4','4'),
    ('5','5'),
    ('6','6'),
    ('7','7'),
    ('8','8'),
    ('9','9'),
    ('10','10'),
)

class Savol(models.Model):
    video = models.ForeignKey(Video, on_delete=models.SET_NULL, null=True, blank=True)
    bilet = models.ForeignKey(Bilet, on_delete=models.SET_NULL, null=True)
    bilet_savol = models.CharField(max_length=2, choices=BILET_SAVOL)
    title_uz = models.CharField(max_length=1000, blank=True)
    title_kr = models.CharField(max_length=1000, blank=True)
    title_ru = models.CharField(max_length=1000, blank=True)
    photo = models.ImageField(upload_to='quiz/img/', blank=True, default='')
    is_photo = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    comment = models.TextField(blank=True)

    def __str__(self):
        return f"{self.title_uz}"

    class Meta:
        verbose_name = 'Test savoli'
        verbose_name_plural = 'Test savollari'

class Javob(models.Model):
    text_uz = models.CharField(max_length=1000, blank=True)
    text_kr = models.CharField(max_length=1000, blank=True)
    text_ru = models.CharField(max_length=1000, blank=True)
    savol = models.ForeignKey(Savol, on_delete=models.SET_NULL,null=True, related_name='answers')
    is_true = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.text_uz}"

    class Meta:
        verbose_name = 'Test javobi'
        verbose_name_plural = 'Test javoblari'


class Result(models.Model):
    question = models.ForeignKey(Savol, on_delete=models.CASCADE, related_name='result_question', null=True)
    answer = models.ForeignKey(Javob, on_delete=models.SET_NULL, related_name='result_answer', null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='result_user', blank=True, null=True)
    created_date = models.DateTimeField(editable=False, default=timezone.now)

    def __str__(self):
        return f"{self.user}"

    class Meta:
        verbose_name = 'Test natijasi'
        verbose_name_plural = 'Test natijalari'

class ResultQuiz(models.Model):
    question = models.ForeignKey(Savol, on_delete=models.CASCADE, related_name='old_result_question', null=True)
    answer = models.ForeignKey(Javob, on_delete=models.SET_NULL, related_name='old_result_answer', null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='old_result_user', blank=True, null=True)
    is_last = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user}"

    class Meta:
        verbose_name = 'Eski natija'
        verbose_name_plural = 'Eski natijalar'

class Attempt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='attempt_user', null=True)
    allowed = fields.IntegerRangeField(verbose_name='Ruxsat berilgan urinishlar',default=2, max_value=3)
    solved = fields.IntegerRangeField(verbose_name='Bajarilgan urinishlar',default=0)

    def __str__(self):
        return f"{self.user}: {self.allowed}"

    class Meta:
        verbose_name = 'Urinish'
        verbose_name_plural = 'Urinishlar'

class ResultJavob(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='resultjavob_user', null=True)
    bilet = models.ForeignKey(Bilet, on_delete=models.SET_NULL, related_name='resultjavob_bilet', null=True)
    j_1 = models.BooleanField(default=False)
    j_2 = models.BooleanField(default=False)
    j_3 = models.BooleanField(default=False)
    j_4 = models.BooleanField(default=False)
    j_5 = models.BooleanField(default=False)
    j_6 = models.BooleanField(default=False)
    j_7 = models.BooleanField(default=False)
    j_8 = models.BooleanField(default=False)
    j_9 = models.BooleanField(default=False)
    j_10 = models.BooleanField(default=False)


class CheckTestColor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='check_bilet_user')
    bilet = models.ForeignKey(Bilet, on_delete=models.CASCADE,)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.bilet}"

templates/dashboard/products/form.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Amaliy mashg'ulot</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
                        <li class="breadcrumb-item active">Amaliy mashg'ulot</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">

                        <form method="post" enctype="multipart/form-data">
                            {#                            {{ form.add_error }}#}
                            {% csrf_token %}
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>Instruktor</label>
                                        <br>
                                        <select name="instructor" >
                                            {% for teacher in teachers %}
                                                <option value="{{ teacher.id }}">{{ teacher.username }}</option>
                                            {% endfor %}
                                        </select>                                        <a href="{% url 'user_create' %}"><i class="fas fa-plus-square" style="color: #0a53be"></i></a>

                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>O'quvchi</label>
                                        <br>
                                        <select name="pupil">
                                            {% for pupil in pupils %}
                                                <option value="{{ pupil.id }}">{{ pupil.username }}</option>
                                            {% endfor %}
                                        </select><a href="{% url 'user_create' %}"><i class="fas fa-plus-square" style="color: #0a53be"></i></a>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>Amaliy mashg'ulotga yozilgan vaqti</label>
                                        <br>
                                        <input type="date" id="id_training_time" name="training_time" required="">
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>Amaliy mashg'ulot holati</label>
                                        <br>
                                        {{ form.status }}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>Bekor qilinganligi</label>
                                        <br>
                                        {{ form.cancel }}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>Amaliy mashg'ulotni bekor qilish sababi</label>
                                        <br>
                                        {{ form.reason_for_cancel }}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>Kim tomonidan bekor qilinganligi</label>
                                        <br>
                                        {{ form.by_whom }}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>Sherik bilan</label>
                                        <br>
                                        {{ form.is_partnership }}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>To'lov to'langanligi</label>
                                        <br>
                                        {{ form.is_payment }}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>To'lov avvaldan</label>
                                        <br>
                                        {{ form.is_prepaid }}
                                    </div>
                                </div>
                            </div>

                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>To'lov bajarilganidan so'ng</label>
                                        <br>
                                        {{ form.is_postpaid }}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>Bonus</label>
                                        <br>
                                        {{ form.is_bonus }}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>Qanday turdagi bonus</label>
                                        <br>
                                        {#                                        {{ form.is_bonus_comment }}#}
                                        <textarea class="form-control" id="id_is_bonus_comment" name="is_bonus_comment"
                                                  rows="3"></textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <label>Bajarildi</label>
                                        <br>
                                        {{ form.done }}
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="alert  alert-default-dark" role="alert">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label>Vaqit</label>
                                            <br>
                                            {#                                            {{ form.created_date }}#}
                                            <input type="date" id="id_created_date" name="created_date" required="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Saqlash</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/dashboard/products/list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Amaliy mashg'ulot</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard'%}">Saytga oʻtish</a></li>
                        <li class="breadcrumb-item active">Amaliy mashg'ulot</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">


                            <div class="card-tools">
                                <a href="{% url 'practical_create' %}">
                                    <div class="btn btn-block btn-outline-success">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                                            <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
                                        </svg>
                                        Qoʻshish
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th>O'qituvchi</th>
                                    <th>O'quvchi</th>
                                    <th>Amaliy M.Y vaqti</th>
                                    <th>Amaliy M holati</th>
                                    <th>Bekor qilinganligi</th>
                                    <th>Amaliy M.Bekor sababi</th>
                                    <th>Kim T.B qilinganligi</th>
                                    <th>Sherik bilan</th>
                                    <th>To'lov to'langanligi</th>
                                    <th>To'lov avvaldan</th>
                                    <th>To'lov B so'ng</th>
                                    <th>Bonus</th>
                                    <th>Qanday turdagi bonus</th>
                                    <th>Bajarildi</th>
                                    <th>Vaqit</th>
                                    <th>Taxrirlash</th>
                                    <th>Oʻchrish</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for i in practical %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ i.instructor }}</td>
                                        <td>{{ i.pupil }}</td>
                                        <td>{{ i.training_time }}</td>
                                        <td>{{ i.status }}</td>
                                        <td>{{ i.cancel }}</td>
                                        <td>{{ i.reason_for_cancel }}</td>
                                        <td>{{ i.by_whom }}</td>
                                        <td>{{ i.is_partnership }}</td>
                                        <td>{{ i.is_payment }}</td>
                                        <td>{{ i.is_prepaid }}</td>
                                        <td>{{ i.is_postpaid }}</td>
                                        <td>{{ i.is_bonus }}</td>
                                        <td>{{ i.is_bonus_comment }}</td>
                                        <td>{{ i.done }}</td>
                                        <td>{{ i.created_date }}</td>
                                        <td style="width: 40px"><a href="{% url 'practical_edit' pk=i.id %}">
                                            <div class="btn btn-block btn-outline-warning">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-pencil-square"
                                                     viewBox="0 0 16 16">
                                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                    <path fill-rule="evenodd"
                                                          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                                </svg>

                                            </div>
                                        </a></td>
                                        <td style="width: 40px"><a href="{% url 'practical_delete' pk=i.id %}">
                                            <div class="btn btn-block btn-outline-danger">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd"
                                                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                </svg>

                                            </div>
                                        </a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
{% endblock %}