landing/urls.py
from django.urls import path, include
from .views import *

app_name = 'landing'

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('home/', home, name='home'),

    path('qabul/', sign_up, name='sign_up'),
    path('kirish/', kirish, name='kirish')

]

onless/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render

from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
from django.views.static import serve

from onless.api import sms_api_result


def trigger_error(request):
    division_by_zero = 1 / 0



urlpatterns = [
                  path('yoz/', admin.site.urls),
                  path('', include('landing.urls')),
                  path('video/', include('video.urls')),

                  path('sms-api-result/', sms_api_result),

                  path('sign/', include('sign.urls')),
                  path('user/', include('user.urls')),
                  path('quiz/', include('quiz.urls')),
                  path('practical/', include('practical.urls')),
                  path('accounts/', include('allauth.urls')),
                  # path('payments/', include('payments.urls')),
                  # path('payments/', include('click.urls')),
                  # path('paycom/', TestView.as_view()),

                  path('click/', include('click.urls')),
                  # path('summernote/', include('django_summernote.urls')),
                  path('sentry-debug/', trigger_error),

                  path('error-403/', TemplateView.as_view(template_name='inc/403.html', ),
                       name='error_403'),
                  path('error-404/', TemplateView.as_view(template_name='inc/404.html', ),
                       name='error_404'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = "user.views.handler404"

quiz/urls.py
from django.urls import path, include
from .views import *

app_name = 'quiz'

urlpatterns = [
    path('add_result/', add_result, name='add_result'),
    path('get-true-answer/', get_true_answer, name='get_true_answer'),
    path('select-lang/', select_lang, name='select_lang'),
    path('select-type/', select_type, name='select_type'),
    path('select-bilet/', select_bilet, name='select_bilet'),
    path('get_bilet_color/', get_bilet_color, name='get_bilet_color'),
    path('reset-answers/', reset_answers, name='reset_answers'),

]

sign/urls.py
from django.urls import path, include
from .views import *

app_name = 'sign'

urlpatterns = [
    path("signs/", sign, name='sign'),
    # path('add-subject/', add_subject, name='add_subject'),
    path('update-schedule/<int:id>/', update_schedule, name='update_schedule'),
    # path('update-subject/<int:id>/', update_subject, name='update_subject'),
    path('delete-schedule/<int:id>/', delete_schedule, name='delete_schedule'),
    path('schedules/', schedules_list, name='schedules_list'),
    path('save-schedule/', save_schedule, name='save_schedule'),
    path('subjects/', subjects_list, name='subjects_list'),
    path('get-subject/', get_subject, name='get_subject'),
    path('get-subject-long-title/', get_subject_long_title, name='get_subject_long_title'),

    path('group-subjects/', group_subjects, name='group_subjects'),
    path('get-schedule/', get_schedule, name='get_schedule'),
    path('materials/', materials, name='materials'),
    path('add-material/', add_material, name='add_material'),
    path('get-video/', get_video, name='get_video'),
    path('delete-material/<int:id>/', delete_material, name='delete_material'),
    # path("traffic_rules/", traffic_rules, name='traffic_rules'),

]

user/urls.py
from django.urls import path, include
from .views import *

app_name = 'user'

urlpatterns = [
    path('', user_login, name='login'),
    path('add/', add_list, name='add_list'),
    path('settings/', settings_list, name='settings_list'),
    path('worker-add/', worker_add, name='worker_add'),
    path('group/<int:id>/add-pupil/', AddPupil.as_view(), name='add_pupil'),
    path('add-group/', add_group, name='add_group'),
    path('groups/', groups_list, name='groups_list'),
    path('group/<int:id>/', group_detail, name='group_detail'),
    path('group-delete/<int:id>/', group_delete, name='group_delete'),
    path('group-update/<int:id>/', group_update, name='group_update'),
    path('profil-edit/', profil_edit, name='edit_profil'),
    path('school-edit/', school_edit, name='edit_school'),
    path('pupil-edit/<int:id>/', pupil_edit, name='edit_pupil'),
    path('contact/', contact, name='contact'),
    path('search/', search, name='search'),
    path('pupil-delete/<int:id>/', pupil_delete, name='pupil_delete'),
    path('workers/', workers_list, name='workers_list'),
    path('worker-edit/<int:id>/', worker_edit, name='worker_edit'),
    path('worker-delete/<int:id>/', worker_delete, name='worker_delete'),
    path('upload-file/', upload_file, name='upload_file'),
    path('group/<int:id>/create-pupil-with-excel/', CreatePupilWithExcel.as_view(), name='create_pupil_with_excel'),
    path('bugalter/groups/', bugalter_groups_list, name='bugalter_groups_list'),
    path('bugalter/group/<int:id>/', bugalter_group_detail, name='bugalter_group_detail'),
    path('set-pay/', set_pay, name='set_pay'),
    path('remove-pay/<int:id>/', remove_pay, name='remove_pay'),
    path('pay-history/<int:user_id>/<int:group_id>/', pay_history, name='pay_history'),
    path('history/view-video/all/', history_view_video_all, name='history_view_video_all'),
    path('history-view-video-all/', HistoryViewVideoAll.as_view(), name='HistoryViewVideoAll'),

    path('history/pupil-view-video/<int:id>/', history_pupil_view_video, name='history_pupil_view_video'),
    path('history-pupil-view-video/<int:id>/', HistoryPupilViewVideo.as_view(), name='HistoryPupilViewVideo'),
    path('get-district/', get_district, name='get_district'),
    path('getDistrict/', getDistrict, name='getDistrict'),

    path('school-groups/<int:id>/', school_groups, name='school_groups'),
    path('school-group/<int:id>/', school_group_detail, name='school_group_detail'),
    path('support/', support, name='support'),
    path('result/<int:id>/', result, name='result'),
    path('news-messages/', news_messages, name='news_messages'),
    path('get-learning-type/', get_learning_type, name='get_learning_type'),

    path('attendance-groups-list/', attendance_groups_list, name='attendance_groups_list'),

    path('attendance-set-by-group/<int:id>/', attendance_set_by_group, name='attendance_set_by_group'),
    path('attendance-set-by-subject/<int:group_id>/<int:subject_id>/', attendance_set_by_subject,
         name='attendance_set_by_subject'),
    path('attendance-set-visited/', attendance_set_visited, name='attendance_set_visited'),
    path('send-sms/', send_sms, name='send_sms'),
    path('send-sms/list/', SendSmsList, name='send_sms_list'),

    path('referral-list/<int:id>/', referral_list, name='referral_list'),

    path('rating-groups-list/', rating_groups_list, name='rating_groups_list'),
    path('rating-set-by-group/<int:id>/', rating_set_by_group, name='rating_set_by_group'),
    path('rating-set-by-subject/<int:group_id>/<int:subject_id>/', rating_set_by_subject, name='rating_set_by_subject'),
    path('electronical-journal/', electronical_journal, name='electronical_journal'),
    path('rating-create/', rating_create, name='rating_create'),
    path('get-group-pupils-count/', get_group_pupils_count, name='get_group_pupils_count'),
    path('get-workers-count/', get_workers_count, name='get_workers_count'),
    # path('get-attendance-time/', get_attendance_time, name='get_attendance_time'),
    path('get-group-months/', get_group_months, name='get_group_months'),
    path('sms-settings/', SmsSettings.as_view(), name='sms_settings'),
    path('buy-simple-sms/', BuySimpleSms.as_view(), name='buy_simple_sms'),
    path('buy-add-pupil-sms/', BuyAddPupilSms.as_view(), name='buy_add_pupil_sms'),

    path('modify-checkbox-send-sms/', modify_checkbox_send_sms, name='modify_checkbox_send_sms'),
    path('payment-payme/', payment_payme, name='payment_payme'),
    path('personal-exam-doc-generate/<int:id>/', personal_exam_doc_generate, name='personal_exam_doc_generate'),

    path('again-send-sms/<int:pupil_id>/', again_send_sms, name='again_send_sms'),

    path('error/403/', error_403, name='error_403'),
    path('handler404/', handler404, name='handler404'),
]

templates/inc/add_list.html
{% extends 'base.html' %}
{% load user_tags %}
{% load sign_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Kiritishlar" "user:add_list" %}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12">
            {% include 'inc/messages_part.html' %}
        </div>
        {% get_count request.user.school.id as count %}
        {% if request.user.role == '2' %}
{#            <div class="col-lg-6 col-md-6 col-sm-12">#}
{#                <!-- small box -->#}
{#                <div class="small-box bg-gradient-cyan">#}
{#                    <div class="inner">#}
{#                        <h3>{{ count.pupils }}</h3>#}
{##}
{#                        <h5>O'quvchi qo'shish</h5>#}
{#                    </div>#}
{#                    <div class="icon">#}
{#                        <i class="fas fa-user-plus"></i>#}
{#                    </div>#}
{##}
{##}
{#                    <a href="{% url 'user:add_pupil' %}" class="small-box-footer"><i class="fas fa-plus"></i></a>#}
{##}
{#                </div>#}
{#            </div>#}

            <div class="col-lg-6 col-md-6 col-sm-12">
                <!-- small box -->
                <div class="small-box bg-lightblue">
                    <div class="inner">

                        <h3>{{ count.workers }}</h3>
                        <h5>Xodim qo'shish</h5>
                    </div>
                    <div class="icon">
                        <i class="fas fa-user-graduate"></i>
                    </div>
                    <a href="{% url 'user:worker_add' %}" class="small-box-footer"><i class="fas fa-plus"></i></a>
                </div>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12">
                <!-- small box -->
                <div class="small-box bg-gradient-cyan">
                    <div class="inner">
                        <h3>{{ count.groups }}</h3>

                        <h5>Guruh qo'shish</h5>
                    </div>
                    <div class="icon">
                        <i class="fas fa-layer-group"></i>
                    </div>
                    <a href="{% url 'user:add_group' %}" class="small-box-footer"><i class="fas fa-plus"></i></a>
                </div>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12">
                <!-- small box -->
                <div class="small-box bg-gradient-lightblue">
                    <div class="inner">
                        {% count_materials request.user.school.id as materials_count %}
                        <h3>{{ materials_count }}</h3>

                        <h5>Material qo'shish</h5>
                    </div>
                    <div class="icon">
                        <i class="fas fa-file-pdf"></i>
                    </div>
                    <a href="{% url 'sign:add_material' %}" class="small-box-footer"><i class="fas fa-plus"></i></a>
                </div>
            </div>

            <!--    <div class="col-lg-6 col-md-6 col-sm-12">-->
            <!--        &lt;!&ndash; small box &ndash;&gt;-->
            <!--        <div class="small-box bg-gradient-lightblue">-->
            <!--            <div class="inner">-->
            <!--                <h3>1</h3>-->

            <!--                <h5>Fan qo'shish</h5>-->
            <!--            </div>-->
            <!--            <div class="icon">-->
            <!--                <i class="fas fa-book"></i>-->
            <!--            </div>-->
            <!--            <a href="#" class="small-box-footer"><i class="fas fa-plus"></i></a>-->
            <!--        </div>-->
            <!--    </div>-->

        {% elif request.user.role == '3' %}

{#            <div class="col-lg-6 col-md-6 col-sm-12">#}
{#                <!-- small box -->#}
{#                <div class="small-box bg-gradient-lightblue">#}
{#                    <div class="inner">#}
{#                        <h3>{{ count.pupils }}</h3>#}
{##}
{#                        <h5>O'quvchi qo'shish</h5>#}
{#                    </div>#}
{#                    <div class="icon">#}
{#                        <i class="fas fa-user-plus"></i>#}
{#                    </div>#}
{#                    <a href="{% url 'user:add_pupil' %}" class="small-box-footer"><i class="fas fa-plus"></i></a>#}
{#                </div>#}
{#            </div>#}

            <div class="col-lg-6 col-md-6 col-sm-12">
                <!-- small box -->
                <div class="small-box bg-gradient-lightblue">
                    <div class="inner">
                        <h3>{{ count.groups }}</h3>

                        <h5>Guruh qo'shish</h5>
                    </div>
                    <div class="icon">
                        <i class="fas fa-layer-group"></i>
                    </div>
                    <a href="{% url 'user:add_group' %}" class="small-box-footer"><i class="fas fa-plus"></i></a>
                </div>
            </div>

            <div class="col-lg-6 col-md-6 col-sm-12">
                <!-- small box -->
                <div class="small-box bg-gradient-lightblue">
                    <div class="inner">
                        {% count_materials request.user.school.id as materials_count %}
                        <h3>{{ materials_count }}</h3>
                        <h5>Material qo'shish</h5>
                    </div>
                    <div class="icon">
                        <i class="fas fa-file-pdf"></i>
                    </div>
                    <a href="{% url 'sign:add_material' %}" class="small-box-footer"><i class="fas fa-plus"></i></a>
                </div>
            </div>


            <!--    <div class="col-lg-6 col-md-6 col-sm-12">-->
            <!--        &lt;!&ndash; small box &ndash;&gt;-->
            <!--        <div class="small-box bg-gradient-lightblue">-->
            <!--            <div class="inner">-->
            <!--                <h3>1</h3>-->

            <!--                <h5>Fan qo'shish</h5>-->
            <!--            </div>-->
            <!--            <div class="icon">-->
            <!--                <i class="fas fa-book"></i>-->
            <!--            </div>-->
            <!--            <a href="#" class="small-box-footer"><i class="fas fa-plus"></i></a>-->
            <!--        </div>-->
            <!--    </div>-->

        {% endif %}


    </div>
{% endblock content %}
{% block bottom %}
    <script>
    $(document).ready(() => {
        Swal.fire({
            title: "Diqqat! Tizimda yangilanish",
            text: "O'quvchi qo'shish uchun guruh ichiga kirib o'quvchi qo'shish tugmasiga bosing!"
        })
    })
    </script>
{% endblock bottom %}

templates/inc/block.html
{% load static %}
<style>

    body {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAABZ0RVh0Q3JlYXRpb24gVGltZQAxMC8yOS8xMiKqq3kAAAAcdEVYdFNvZnR3YXJlAEFkb2JlIEZpcmV3b3JrcyBDUzVxteM2AAABHklEQVRIib2Vyw6EIAxFW5idr///Qx9sfG3pLEyJ3tAwi5EmBqRo7vHawiEEERHS6x7MTMxMVv6+z3tPMUYSkfTM/R0fEaG2bbMv+Gc4nZzn+dN4HAcREa3r+hi3bcuu68jLskhVIlW073tWaYlQ9+F9IpqmSfq+fwskhdO/AwmUTJXrOuaRQNeRkOd5lq7rXmS5InmERKoER/QMvUAPlZDHcZRhGN4CSeGY+aHMqgcks5RrHv/eeh455x5KrMq2yHQdibDO6ncG/KZWL7M8xDyS1/MIO0NJqdULLS81X6/X6aR0nqBSJcPeZnlZrzN477NKURn2Nus8sjzmEII0TfMiyxUuxphVWjpJkbx0btUnshRihVv70Bv8ItXq6Asoi/ZiCbU6YgAAAABJRU5ErkJggg==);
    }

    .error-template {
        text-align: center;
        margin-top: 15%;
    }

    .error-actions {
        margin-top: 15px;
        margin-bottom: 15px;
    }

    .error-actions .btn {
        margin-right: 10px;
    }
</style>

<link href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" id="bootstrap-css">
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>{#<script src="{% static '' %}//code.jquery.com/jquery-1.11.1.min.js"></script>#}
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!</h1>
                <h2>
                    Siz bloklangansiz !</h2>
                <div class="error-details">
                    Kechirasiz, Sizning avtomaktabingiz bloklangan.
                <br>
                    Ma'lumot uchun {% if request.user.school.phone %}{{ request.user.school.phone }}{% endif %} raqamiga bog'laning !
                </div>
                <div class="error-actions">
                    <a href="{% url 'video:home' %}" class="btn btn-primary btn-lg"><span
                            class="glyphicon glyphicon-home"></span>
                        Bosh sahifa</a><a href="https://t.me/onless_support" class="btn btn-secondary btn-lg"><span
                        class="glyphicon glyphicon-envelope"></span> Biz bilan aloqa </a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/inc/breadcumb.html
{#<ul>#}
{#    {% for parent in category.get_ancestors %}#}
{#        <li><a href="/category/{{ parent.id }}/">{{ parent.name }}</a></li>#}
{#    {% endfor %}#}
{#    <li><a href="/category/{{ category.id }}/">{{ category.name }}</a></li>#}
{#</ul>#}


{#{% load mptt_tags %}#}
{#{% recursetree categories %}#}
{#    <nav aria-label="breadcrumb">#}
{#        <ol class="breadcrumb">#}
{#            {% for category in categories %}#}
{#                {% if category.parent %}#}
{#                    <li class="breadcrumb-item"><a href="">Bosh sahifa</a></li>#}
{#                    <li class="breadcrumb-item " aria-current="page">{{ category.parent }}</li>#}
{#                    {% if not node.is_leaf_node %}#}
{#                        <li>#}
{#                            {{ category.title }}#}
{#                        </li>#}
{#                    {% endif %}#}
{#                {% endif %}#}
{#            {% endfor %}#}
{#        </ol>#}
{#    </nav>#}
{#{% endrecursetree %}#}

<ul class="breadcrumb">
    {% for url, label in breadcrumbs %}
        <li>
            {% ifnotequal forloop.counter breadcrumbs_total %}
                <a href="{{ url }}">{{ label|safe }}</a>
            {% else %}
                {{ label|safe }}
            {% endifnotequal %}
            {% if not forloop.last %}
                <span class="divider">/</span>
            {% endif %}
        </li>
    {% endfor %}
</ul>

templates/inc/footer.html
 <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
Onlayn darslar platformasi    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2018-{% now "Y" %} <a href="http://sierus.uz">SIERUS GROUP</a>.</strong> All rights reserved.

  </footer>

templates/inc/messages_part.html
{% if messages %}
    {% for message in messages %}
        {% if forloop.last %}
            <div class="alert alert-{% if message.tags == 'success' %}success{% elif message.tags == 'error' %}danger{% else %}warning{% endif %}">
                <a class="close" href="#" data-dismiss="alert">×</a>
                {{ message|safe }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}
{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
{% load static %}
{% load humanize %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" style="color: blue" data-widget="pushmenu" href="#" role="button"><i id="menu_icon"
                                                                                                     class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'landing:home' %}" class="nav-link">Bosh sahifa</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'user:contact' %}" class="nav-link">Aloqa</a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3" action="{% url 'user:search' %}" method="get">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" name="q" type="text"
                   placeholder="{% if q %}{{ q }}{% else %}Qidiruv...{% endif %}"
                   aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>


    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

        {% if request.user.role == '2' %}
            <li class="nav-item dropdown" id="account_settings_dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="true">
                    <i style="font-size: 1.5em" class="fas fa-school"></i> <b id="school_name"
                                                                              style="height: auto">{{ request.user.school }}</b>
                </a>
                <div style="width: 18rem !important;" class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <div class="text-left ml-2"><i class="fas fa-money-check ml-2 mr-2"></i>Hisob: <span
                            class="ml-2">{% if request.user.school.money %}
                        {{ request.user.school.money|intcomma }} so'm{% else %}0 so'm{% endif %} <a id="addAmountBtn"
                                                                                                    href="#"><i
                            style="font-size: 1.2em" class="fas fa-plus-circle ml-3 pt-2"></i></a></span>
                    </div>
                    <hr>
                    <div class="text-left ml-2"><i class="fas fa-envelope ml-2 mr-2"></i>Kiritish sms soni: <span
                            class="ml-2">{% if request.user.school.add_pupil_sms_count %}
                        {{ request.user.school.add_pupil_sms_count }}{% else %}0{% endif %}</span>
                    </div>
                    <div class="text-left ml-2"><i class="fas fa-envelope ml-2 mr-2"></i>Smslar soni: <span
                            class="ml-2">{% if request.user.school.sms_count %}
                        {{ request.user.school.sms_count }} ta{% else %}0 ta{% endif %}</span>
                    </div>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" style="color: blue" href="{% url 'user:sms_settings' %}"><i
                            class="fas fa-cogs"></i>&nbsp&nbspSMS Sozlamalar</a>
                </div>
            </li>
        {% endif %}
        {% if request.user.is_authenticated %}
            <a class="btn btn-danger" href="/accounts/logout">Chiqish</a>
        {% endif %}
        <!-- Messages Dropdown Menu -->
        {#        <li class="nav-item dropdown">#}
        {#            <a class="nav-link" data-toggle="dropdown" href="#">#}
        {#                <i class="far fa-comments"></i>#}
        {#                <span class="badge badge-danger navbar-badge">3</span>#}
        {#            </a>#}
        {#            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">#}
        {#                <a href="#" class="dropdown-item">#}
        {#                    <!-- Message Start -->#}
        {#                    <div class="media">#}
        {#                        <img src="{% static 'img/user1-128x128.jpg' %}" alt="User Avatar"#}
        {#                             class="img-size-50 mr-3 img-circle">#}
        {#                        <div class="media-body">#}
        {#                            <h3 class="dropdown-item-title">#}
        {#                                {% if user.is_authenticated %}#}
        {#                                    {{ request.user.username }}#}
        {#                                {% endif %}#}
        {#                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>#}
        {#                            </h3>#}
        {#                            <p class="text-sm"></p>#}
        {#                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>#}
        {#                        </div>#}
        {#                    </div>#}
        {#                    <!-- Message End -->#}
        {#                </a>#}
        {#                <div class="dropdown-divider"></div>#}
        {#                <a href="#" class="dropdown-item">#}
        {#                    <!-- Message Start -->#}
        {#                    <div class="media">#}
        {#                        <img src="{% static 'img/user8-128x128.jpg' %}" alt="User Avatar"#}
        {#                             class="img-size-50 img-circle mr-3">#}
        {#                        <div class="media-body">#}
        {#                            <h3 class="dropdown-item-title">#}
        {#                                John Pierce#}
        {#                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>#}
        {#                            </h3>#}
        {#                            <p class="text-sm">I got your message bro</p>#}
        {#                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>#}
        {#                        </div>#}
        {#                    </div>#}
        {#                    <!-- Message End -->#}
        {#                </a>#}
        {#                <div class="dropdown-divider"></div>#}
        {#                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>#}
        {#            </div>#}
        {#        </li>#}
        {#        <!-- Notifications Dropdown Menu -->#}
        {#        <li class="nav-item dropdown">#}
        {#            <a class="nav-link" data-toggle="dropdown" href="#">#}
        {#                <i class="far fa-bell"></i>#}
        {#                <span class="badge badge-warning navbar-badge">15</span>#}
        {#            </a>#}
        {#            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">#}
        {#                <span class="dropdown-header">15 Notifications</span>#}
        {#                <div class="dropdown-divider"></div>#}
        {#                <a href="#" class="dropdown-item">#}
        {#                    <i class="fas fa-envelope mr-2"></i> 4 new messages#}
        {#                    <span class="float-right text-muted text-sm">3 mins</span>#}
        {#                </a>#}
        {#                <div class="dropdown-divider"></div>#}
        {#                <a href="#" class="dropdown-item">#}
        {#                    <i class="fas fa-users mr-2"></i> 8 friend requests#}
        {#                    <span class="float-right text-muted text-sm">12 hours</span>#}
        {#                </a>#}
        {#                <div class="dropdown-divider"></div>#}
        {#                <a href="#" class="dropdown-item">#}
        {#                    <i class="fas fa-file mr-2"></i> 3 new reports#}
        {#                    <span class="float-right text-muted text-sm">2 days</span>#}
        {#                </a>#}
        {#                <div class="dropdown-divider"></div>#}
        {#                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>#}
        {#            </div>#}
        {#        </li>#}
        {#        <li class="nav-item">#}
        {#            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i#}
        {#                    class="fas fa-th-large"></i></a>#}
        {#        </li>#}
    </ul>
</nav>
<!-- /.navbar -->

{#<div class="alert alert-dark text-center"><b>DIQQAT! Tizim test rejimida ishlamoqda! Tizim bo'yicha savollar bo'lganda#}
{#    <a href="https://t.me/onless_support" style="color: #60c4f5; text-decoration: none"><i class="fab fa-telegram"></i>#}
{#        Telegram guruh </a>ga yozing</b></div>#}